-- V6: Sales schema
CREATE TABLE customers (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    customer_code VARCHAR(20) NOT NULL UNIQUE,
    name VARCHAR(200) NOT NULL,
    contact_person VARCHAR(100),
    phone VARCHAR(20),
    email VARCHAR(100),
    address_line1 VARCHAR(200),
    address_line2 VARCHAR(200),
    city VARCHAR(100),
    state VARCHAR(100),
    pincode VARCHAR(10),
    gst_number VARCHAR(20),
    pan_number VARCHAR(15),
    credit_limit DECIMAL(15,2) DEFAULT 0,
    outstanding_amount DECIMAL(15,2) DEFAULT 0,
    payment_terms VARCHAR(200),
    payment_days INT DEFAULT 30,
    status ENUM('ACTIVE','INACTIVE','BLOCKED','CREDIT_HOLD') NOT NULL DEFAULT 'ACTIVE',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by VARCHAR(50) DEFAULT 'system',
    updated_by VARCHAR(50)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE sales_orders (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    so_number VARCHAR(30) NOT NULL UNIQUE,
    customer_id BIGINT NOT NULL,
    warehouse_id BIGINT,
    product_id BIGINT NOT NULL,
    grade_id BIGINT,
    quantity DECIMAL(12,3) NOT NULL,
    rate DECIMAL(12,2) NOT NULL,
    total_amount DECIMAL(15,2) NOT NULL,
    gst_amount DECIMAL(12,2) DEFAULT 0,
    grand_total DECIMAL(15,2) NOT NULL,
    delivery_date DATE,
    delivery_address VARCHAR(500),
    payment_terms VARCHAR(200),
    status ENUM('DRAFT','PENDING_APPROVAL','APPROVED','REJECTED','ALLOCATED','DISPATCHED','PARTIALLY_DELIVERED','DELIVERED','INVOICED','COMPLETED','CANCELLED') NOT NULL DEFAULT 'DRAFT',
    dispatched_quantity DECIMAL(12,3) DEFAULT 0,
    delivered_quantity DECIMAL(12,3) DEFAULT 0,
    notes TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by VARCHAR(50) DEFAULT 'system',
    updated_by VARCHAR(50),
    FOREIGN KEY (customer_id) REFERENCES customers(id),
    FOREIGN KEY (product_id) REFERENCES products(id),
    FOREIGN KEY (grade_id) REFERENCES grades(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX idx_so_number ON sales_orders(so_number);
CREATE INDEX idx_so_customer ON sales_orders(customer_id);
CREATE INDEX idx_so_status ON sales_orders(status);

CREATE TABLE dispatches (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    dispatch_number VARCHAR(30) NOT NULL UNIQUE,
    sales_order_id BIGINT NOT NULL,
    warehouse_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    grade_id BIGINT,
    quantity DECIMAL(12,3) NOT NULL,
    vehicle_id BIGINT,
    driver_id BIGINT,
    trip_id BIGINT,
    dispatch_date DATETIME,
    status ENUM('DRAFT','READY','LOADING','DISPATCHED','IN_TRANSIT','DELIVERED','COMPLETED','CANCELLED') NOT NULL DEFAULT 'DRAFT',
    dispatched_by BIGINT,
    notes VARCHAR(500),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by VARCHAR(50) DEFAULT 'system',
    updated_by VARCHAR(50),
    FOREIGN KEY (sales_order_id) REFERENCES sales_orders(id),
    FOREIGN KEY (warehouse_id) REFERENCES warehouses(id),
    FOREIGN KEY (product_id) REFERENCES products(id),
    FOREIGN KEY (vehicle_id) REFERENCES vehicles(id),
    FOREIGN KEY (driver_id) REFERENCES drivers(id),
    FOREIGN KEY (dispatched_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE deliveries (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    delivery_number VARCHAR(30) NOT NULL UNIQUE,
    dispatch_id BIGINT NOT NULL,
    sales_order_id BIGINT NOT NULL,
    trip_id BIGINT,
    delivered_quantity DECIMAL(12,3) NOT NULL,
    delivery_date DATETIME NOT NULL,
    received_by_name VARCHAR(100),
    received_by_phone VARCHAR(20),
    pod_document_url VARCHAR(500),
    pod_uploaded_at DATETIME,
    pod_verified BOOLEAN DEFAULT FALSE,
    status ENUM('PENDING','DELIVERED','CONFIRMED','DISPUTED') NOT NULL DEFAULT 'PENDING',
    notes VARCHAR(500),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by VARCHAR(50) DEFAULT 'system',
    updated_by VARCHAR(50),
    FOREIGN KEY (dispatch_id) REFERENCES dispatches(id),
    FOREIGN KEY (sales_order_id) REFERENCES sales_orders(id),
    FOREIGN KEY (trip_id) REFERENCES trips(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE invoices (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    invoice_number VARCHAR(30) NOT NULL UNIQUE,
    sales_order_id BIGINT NOT NULL,
    customer_id BIGINT NOT NULL,
    delivery_id BIGINT,
    invoice_date DATE NOT NULL,
    due_date DATE NOT NULL,
    subtotal DECIMAL(15,2) NOT NULL,
    gst_amount DECIMAL(12,2) DEFAULT 0,
    total_amount DECIMAL(15,2) NOT NULL,
    paid_amount DECIMAL(15,2) DEFAULT 0,
    outstanding_amount DECIMAL(15,2) NOT NULL,
    status ENUM('DRAFT','ISSUED','PARTIALLY_PAID','PAID','OVERDUE','CANCELLED') NOT NULL DEFAULT 'DRAFT',
    notes TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by VARCHAR(50) DEFAULT 'system',
    updated_by VARCHAR(50),
    FOREIGN KEY (sales_order_id) REFERENCES sales_orders(id),
    FOREIGN KEY (customer_id) REFERENCES customers(id),
    FOREIGN KEY (delivery_id) REFERENCES deliveries(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
